name: wavediff-env
channels:
  - conda-forge
dependencies:
  - cudatoolkit=11.2
  - cudnn=8.1
  - tensorflow=2.11
  - tensorflow-gpu=2.11
  - pip
  - pip:
      - astropy
      - galsim
      - matplotlib
      - opencv-python
      - pandas
      - pillow
      - seaborn
      - scipy
      - tensorflow-addons>=0.21.0
      - zernike