# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CD_Manual

on: [workflow_dispatch]

jobs:
  docs:
    name: Test API documentation build
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.11"

      - name: Check Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install ".[docs]"

      - name: Build API documentation
        run: |
          make -C docs clean
          make -C docs html

      - name: Archive documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          publish_dir: docs/build/html
